/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function Button3D({ onHoverButton, hideModal, ...props }) {
  const textRef = useRef();
  const { nodes, materials } = useGLTF("/button.glb");
  const white = new THREE.Color("White");
  const yellow = new THREE.Color("Yellow");

  return (
    <group
      {...props}
      dispose={null}
      onPointerEnter={() => {
        onHoverButton([textRef]);
        textRef.current.material.color = white;
      }}
      onPointerLeave={() => {
        onHoverButton(null);
        textRef.current.material.color = yellow;
      }}
      onClick={() => hideModal(false)}
    >
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        ref={textRef}
        geometry={nodes.Text.geometry}
        material-color={"yellow"}
        position={[-0.07, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Material.001"]}
        position={[-0.05, -0.02, 0]}
        scale={[1.39, 0.95, 0.55]}
      />
    </group>
  );
}

useGLTF.preload("/button.glb");
