/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";

export default function Button3D({ onHover, ...props }) {
  const textRef = useRef();
  const { nodes, materials } = useGLTF("/button.glb");

  return (
    <group
      {...props}
      dispose={null}
      onPointerOver={() => onHover([textRef])}
      onPointerOut={() => onHover(null)}
    >
      <mesh geometry={nodes.Plane.geometry} material-color="black" />
      <mesh
        ref={textRef}
        geometry={nodes.Text.geometry}
        material-color={"white"}
        position={[-0.07, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material-color="orange"
        position={[-0.05, -0.02, 0]}
        scale={[1.39, 0.95, 0.55]}
      />
    </group>
  );
}

useGLTF.preload("/button.glb");
