/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Button3D({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/button.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
      <mesh
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        position={[-0.07, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/button.glb");
