/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ onHoverEmail, ...props }) {
  const iconRef = useRef();
  const { nodes, materials } = useGLTF("/email.glb");
  return (
    <group
      {...props}
      dispose={null}
      onPointerOver={() => onHoverEmail([iconRef])}
      onPointerOut={() => onHoverEmail(null)}
    >
      <mesh
        ref={iconRef}
        geometry={nodes.Curve001.geometry}
        material={materials.Material}
        position={[0, 0, 0.01]}
        scale={3.44}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
        scale={[0.21, 0.16, 0.16]}
      />
    </group>
  );
}

useGLTF.preload("/email.glb");
