/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/linkedin.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} scale={0.51} />
      <mesh geometry={nodes.Object.geometry} material={materials['Material.001']} position={[0, 0.04, 0]} scale={0.7} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.002']} position={[0, 0.01, 0.01]} scale={0.42} />
    </group>
  )
}

useGLTF.preload('/linkedin.glb')
