/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Linkedin3D({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/linkedin.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        scale={0.51}
      />
      <mesh
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        scale={0.7}
      />
    </group>
  );
}

useGLTF.preload("/linkedin.glb");
