/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Linkedin3D({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/linkedin.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials["SVGMat.001"]}
      />
    </group>
  );
}

useGLTF.preload("/linkedin.glb");
