/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Terrain({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/terrain.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-2.46, 0.37, -3.46]}>
        <mesh geometry={nodes.Cylinder067.geometry} material={materials.wood} />
        <mesh
          geometry={nodes.Cylinder067_1.geometry}
          material={materials.meatl}
        />
      </group>
      <mesh
        geometry={nodes.Fence.geometry}
        material={materials.wood}
        position={[-1.66, -0.1, 7.56]}
        rotation={[-1.59, 0.01, -1.67]}
      />
      <group position={[-0.86, -2.07, -1.5]}>
        <mesh
          geometry={nodes.Cylinder030.geometry}
          material={materials.grass}
        />
        <mesh
          geometry={nodes.Cylinder030_1.geometry}
          material={materials.stone}
        />
      </group>
      <mesh
        geometry={nodes.Path.geometry}
        material={materials["Material.006"]}
        position={[1.65, -0.45, 0.96]}
        rotation={[0.01, 0, 0.02]}
      />
      <group position={[-7.86, -0.2, -2.92]} rotation={[0, -0.07, 0]}>
        <mesh geometry={nodes.Cylinder056.geometry} material={materials.wood} />
        <mesh
          geometry={nodes.Cylinder056_1.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group position={[-0.39, -0.37, 5.95]}>
        <mesh geometry={nodes.Cylinder062.geometry} material={materials.wood} />
        <mesh
          geometry={nodes.Cylinder062_1.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere.geometry}
        material={materials.stone}
        position={[1.22, -0.68, 4.98]}
        rotation={[0.55, 0.17, 0.78]}
      />
      <mesh
        geometry={nodes.Icosphere001.geometry}
        material={materials.stone}
        position={[-6.31, -0.96, 3.73]}
        rotation={[0.55, 0.17, 0.78]}
      />
      <mesh
        geometry={nodes.Icosphere002.geometry}
        material={materials.stone}
        position={[6.65, -0.53, -2.99]}
        rotation={[1.68, -0.16, -0.16]}
      />
      <mesh
        geometry={nodes.Icosphere003.geometry}
        material={materials.stone}
        position={[3.43, -0.55, -5.76]}
        rotation={[1.52, -0.54, 0.02]}
      />
      <mesh
        geometry={nodes.Icosphere005.geometry}
        material={materials.stone}
        position={[-5.73, -0.81, 0.37]}
        rotation={[-0.55, -0.24, 1.48]}
      />
      <mesh
        geometry={nodes.Icosphere006.geometry}
        material={materials["stone.001"]}
        position={[-4.66, -0.62, 1.26]}
        rotation={[-0.55, -0.24, 1.48]}
      />
      <mesh
        geometry={nodes.Icosphere007.geometry}
        material={materials["stone.001"]}
        position={[-5.79, -0.75, 1.4]}
        rotation={[-0.86, -0.67, -0.25]}
      />
      <mesh
        geometry={nodes.Icosphere008.geometry}
        material={materials["stone.001"]}
        position={[6.61, -0.5, -1.85]}
        rotation={[3.12, -0.55, 0.9]}
      />
      <mesh
        geometry={nodes.Icosphere009.geometry}
        material={materials["stone.001"]}
        position={[5.61, -0.49, -2.17]}
        rotation={[0.31, -0.88, -0.82]}
      />
      <mesh
        geometry={nodes.Icosphere010.geometry}
        material={materials["stone.001"]}
        position={[3.33, -0.64, 5.69]}
        rotation={[0.31, -0.88, -0.82]}
      />
      <mesh
        geometry={nodes.Cube101.geometry}
        material={materials["Material.008"]}
        position={[0.41, -0.21, 6.4]}
        rotation={[0, 0.18, 0]}
      />
      <mesh
        geometry={nodes.Cube103.geometry}
        material={materials["Material.008"]}
        position={[-2.54, -0.21, 3.63]}
        rotation={[0, 0.18, 0]}
      />
      <mesh
        geometry={nodes.Cube104.geometry}
        material={materials["Material.008"]}
        position={[-8.65, -0.21, 1.97]}
        rotation={[0, 0.18, 0]}
      />
      <mesh
        geometry={nodes.Cube105.geometry}
        material={materials["Material.008"]}
        position={[2.82, 0.06, 0.5]}
        rotation={[0, -1.01, 0]}
      />
      <mesh
        geometry={nodes.Cube106.geometry}
        material={materials["Material.008"]}
        position={[-4.08, -0.21, -2.06]}
        rotation={[0, 0.18, 0]}
      />
      <mesh
        geometry={nodes.Cube108.geometry}
        material={materials["Material.008"]}
        position={[7.72, -0.07, -2.36]}
        rotation={[-Math.PI, 1.14, -Math.PI]}
      />
      <mesh
        geometry={nodes.Cube109.geometry}
        material={materials["Material.008"]}
        position={[6.9, -0.21, 3.49]}
        rotation={[Math.PI, -0.39, Math.PI]}
      />
      <mesh
        geometry={nodes.Cube110.geometry}
        material={materials["Material.008"]}
        position={[3.46, -0.16, 3]}
        rotation={[Math.PI, -1.29, Math.PI]}
      />
      <mesh
        geometry={nodes.Cube111.geometry}
        material={materials["Material.008"]}
        position={[-5.42, -0.41, 4.29]}
        rotation={[0, -0.55, 0]}
      />
      <mesh
        geometry={nodes.Cube112.geometry}
        material={materials["Material.008"]}
        position={[3.59, -0.02, -3.08]}
        rotation={[0, 0.69, 0]}
      />
      <mesh
        geometry={nodes.Cube107.geometry}
        material={materials["Material.008"]}
        position={[1.89, 0.16, -8.4]}
        rotation={[0, 0.18, 0]}
      />
    </group>
  );
}

useGLTF.preload("/terrain.glb");
