import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Canvas } from "@react-three/fiber";
import Box from "../objects/box";
import Avatar from "../objects/Avatar";
import { OrbitControls, PerspectiveCamera, Text } from "@react-three/drei";
import { Suspense, useRef, useEffect } from "react";
import WelcomeText from "../objects/WelcomeText";

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Canvas style={{ width: "100vw", height: "100vh" }}>
        <Suspense fallback={null}>
          <gridHelper />
          <axesHelper />
          <OrbitControls
            enableZoom={false}
            enablePan={false}
            //for locking the rotation only in sideways
            maxPolarAngle={1.5}
            //for locking the rotation only in sideways
            minPolarAngle={1.5}
            //for rotating camera up or down in x,y,z
            target={[0, 1.5, 0]}
          />
          <PerspectiveCamera
            makeDefault
            //this is for moving camera position up or down in x,y,z
            position={[0, 3, 0]}
          />

          <ambientLight />
          <pointLight position={[10, 10, 10]} />
          <WelcomeText />
          <Avatar position={[1, 0, -2]} rotation={[0, -0.3, 0]} />
        </Suspense>
      </Canvas>
    </div>
  );
}
